### ISSUE TITLE
[ENGINE] Fork Fontkit?

### ISSUE THREAD

**Issue by RoelN** [Wakamai-Fondue/wakamai-fondue#18]
It may be worth seeing if we can fork Fontkit:

- Merge some of the useful open PRs
- Add some functionality now being bolted on by WF
- Strip it of stuff we don't need
  - SVG conversion
  - Font export
  - "Performing layout"
  - Subsetting
  - Path objects

**Comment by RoelN** [comment]
It's worth noting that https://github.com/Pomax/Font.js looks like it provides much of what we'd need from a stripped-down Fontkit. Might be quicker to move to this than wrangling Fontkit into submission!

**Comment by Pomax** [comment]
at the very least, it'd probably be faster to start with fontjs even if fontkit stripping happens in parallel

**Comment by jnieberg** [comment]
This PR is fixed
