### ISSUE TITLE
Show how text looks in other browser and operating systems

### ISSUE THREAD

**Issue by bramstein** [Wakamai-Fondue/wakamai-fondue#26]
There are still quite a few rasterization differences across platforms and browsers. I think it would be great for users to see what a font will look like in different circumstances.

**Comment by RoelN** [comment]
I think opening WF in the browser of your choice is a flexible way of doing that. And a lot less complex than trying to embed render systems, or hook up to a service like BrowserStack :-) So I'm closing this for now — thanks anyway!
